### ISSUE TITLE
Cant send any Pictures/Images with sendfile

### ISSUE THREAD

**Issue by AWildLeon** [erikdelange/MicroPython-HTTP-Server#1]
Hey Everytime i try to get the favicon it throws an error

it's the example code, with added code to log in to Wi-Fi
Platform: Raspberry Pi Pico W

error:

```request_line b'GET /favicon.ico HTTP/1.1\r\n' from [IP Address]
global exception handler: {'exception': OSError(2,), 'future': <Task>, 'message': "Task exception wasn't retrieved"}
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "ahttpserver/server.py", line 113, in _handle_request
  File "ahttpserver/server.py", line 102, in _handle_request
  File "<stdin>", line 53, in favicon
  File "ahttpserver/sendfile.py", line 16, in sendfile
OSError: [Errno 2] ENOENT
HTTP server stopped

**Comment by erikdelange** [comment]
Hi, I can reproduce this error by deleting file "favicon.ico" from my microcontrollers filesystem. It looks like file "favicon.ico" cannot be found (hence ENOENT) on your microcontrollers filesystem. Could you try downloading it from this repo and then put it in the same directory as "index.html"?  Please let me know if this solves your problem.

**Comment by AWildLeon** [comment]
I already checked that, and both files are in the same directory, I've tried with your example code (ademo.py) I just added Wi-Fi login, and I uploaded the full repo with the icon (same structure nothing changed). In my normal code, I have the same issue.

**Comment by AWildLeon** [comment]
With curl, it doesn't throw it, just returns nothing besides the headers

**Comment by erikdelange** [comment]
Weird (and hard to figure out from a distance). To be sure I just loaded all code and data from the repo on an empty microcontroller. When just getting the favicon then curl's response should look like this:

> C:\Windows\System32>curl -i http://192.168.178.11/favicon.ico
HTTP/1.1 200 OK
Content-Type: image/x-icon
Connection: close
 
> Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

If I change the filename of the favicon file in ademo.py to "does_not_exist_favicon.ico" like this
```python
@app.route("GET", "/favicon.ico")
async def favicon(reader, writer, request):
    response = HTTPResponse(200, "image/x-icon", close=True)
    await response. Send(writer)
    await writer. Drain()
    await sendfile(writer, "does_not_exist_favicon.ico")
```
and restart the server then curl returns
> C:\Windows\System32>curl -i http://192.168.178.11/favicon.ico
HTTP/1.1 200 OK
Content-Type: image/x-icon
Connection: close

which is expected as the response headers are sent but the server fails when sending the message body. The microcontroller output shows

> MicroPython v1.19.1 on 2022-11-03; ESP32 module (spiram) with ESP32
Type "help()" for more information.

> %run -c $EDITOR_CONTENT

> hello 0
HTTP server started on 0.0.0.0:80
request_line b'GET /favicon.ico HTTP/1.1\r\n' from 192.168.178.186
global exception handler: {'future': <Task>, 'message': "Task exception wasn't retrieved", 'exception': OSError(2,)}
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "/lib/ahttpserver/server.py", line 113, in _handle_request
  File "/lib/ahttpserver/server.py", line 102, in _handle_request
  File "<stdin>", line 42, in favicon
  File "/lib/ahttpserver/sendfile.py", line 16, in sendfile
OSError: [Errno 2] ENOENT
HTTP server stopped

which matches the error you posted initially. This is caused by the _open()_ call in ahttpserver\sendfile.py. The error occurs before the actual content of the file is even read.

What happens if you try _open("favicon.ico", "rb")_ from the micropython REPL?

I would expect this output (first one is successful, the second example fails because the file does not exist).
>>> open("favicon.ico", "rb")
<io.FileIO>

>>> open("does_not_exist_favicon.ico", "rb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 2] ENOENT

**Comment by AWildLeon** [comment]
I will try it out tomorrow at work

**Comment by AWildLeon** [comment]
I got it working, it was a bug with my IDE (VS Code) not uploading binary files

```
>>> import os
>>> os.listdir()
['LICENSE', 'ademo.py', 'ahttpserver', 'demo.py', 'httpserver', 'index.html', 'project.pico-w-go']
```

After using another program to upload:
```
>>> os.listdir()
['LICENSE', 'README.md', 'ademo.py', 'ahttpserver', 'demo.py', 'favicon.ico', 'httpserver', 'index.html', 'project.pico-w-go']
```

What IDE are you using?

Btw: Thanks for the nice project, you saved me a lot of work :D

**Comment by erikdelange** [comment]
Good to hear.
I use FileZilla to manage files on my microcontroller. The GUI enables you to see what you are doing. For FileZilla to work you need to start an FTP server on the microcontroller. The one I use is _uftpd.py_ from https://github.com/robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD. Import it in your _main.py_ after you have connected to the WiFi. For editing I use VS Code, and to start programs at the REPL I use Thonny. You can also use Thonny to move files from and to your microcontroller, but it is not as fancy as FileZilla.
